### ISSUE TITLE
(BUG) Al hacer click en el botón "inscribirme".

### ISSUE THREAD

**Issue by joseqr23** [linder3hs/Tech-Conf#1]
### Si se hace click más de una vez en el botón "inscribirme", se agregan eventos repetidos.
![fix2](https://user-images.githubusercontent.com/113225090/221760337-c9f6ed47-9395-4c7d-b960-2f16d4f28a6a.PNG)

**Comment by linder3hs** [comment]
fue resulto en este PR
https://github.com/linder3hs/Tech-Conf/pull/2
