### ISSUE TITLE
Los elementos asociados con el login siempre tardan en cargar.

### ISSUE THREAD

**Issue by MDCIrony** [linder3hs/Tech-Conf#4]
# Los elementos asociados con el login siempre tardan en cargar.

## Descripción
Todos los elementos asociados al inicio de sesión tardan en ser renderizados en la página, y en su defecto, siempre se colocan los que por defecto estarían cuando no estás logueado (por 1 seg aprox). En esta ventana de tiempo puedes interactuar con los botones y elementos visibles.

## Pasos para reproducir el problema
1. Iniciar sesión
2. Navegar a sección Eventos (o sección mis tickets)

## Capturas de pantalla

En esta imagen se puede ver que estoy logueado pero se muestra [`Ver Tickets`] de todos los eventos (incluso de los que no estoy inscrito). Esto dura 1-2 segundos (la primera carga de la página) y puedes interactuar con los botones Ver Ticket (debería salis `Inscribirme`).
![imagen](https://user-images.githubusercontent.com/86406248/222076400-0982436c-fba4-43b5-8302-dd63bc93c797.png)

Por ejemplo, al hacer click en mis tickets (ya con el login realizado), se muestra como si no estuviera logueado por alrededor de 1 segundo.  (En la imagen siguiente ya me encontraba logueado, 1 seg después carga con normalidad y se muestra mi foto de perfil y mis tickets).

![imagen](https://user-images.githubusercontent.com/86406248/222085243-26c70dcb-45eb-45e1-95ea-d9870d6687ef.png)

## Información adicional
Lo mismo sucede con el logo de login de Github en todas las ventanas, aunque este tarda menos en cargar, puede hacerse click sobre el y "volver a forzar el login" redirigiendo al landing.

**Comment by linder3hs** [comment]
corregido 

https://github.com/linder3hs/Tech-Conf/pull/8

**Comment by linder3hs** [comment]
ready
