### ISSUE TITLE
No carga las imagenes o no tiene imagenes

### ISSUE THREAD

**Issue by Kishinkidu** [linder3hs/Tech-Conf#7]
![image](https://user-images.githubusercontent.com/95624124/222329134-feb2cc01-e36f-4fef-a753-e43f7f6d2212.png)

**Comment by linder3hs** [comment]
Hola porfa me puedes indicar como replicar el error.

**Comment by joehann-9s** [comment]
> Hola porfa me puedes indicar como replicar el error.
El bug ocurre en el navegador Brave.

**Comment by linder3hs** [comment]
solucionado, para arreglar este
<img width="1728" alt="Screenshot 2023-03-02 at 14 47 23" src="https://user-images.githubusercontent.com/20673011/222536402-5996aef7-c966-4555-960b-ac4958ce9594.png">
 error se tuvo que cambiar el origen de las imagenes
