### ISSUE TITLE
El logo de Github en los tickets propios no se ve (página Mis Tickets).

### ISSUE THREAD

**Issue by MDCIrony** [linder3hs/Tech-Conf#9]
## Descripción

El logo de github en la vista de los tickets para eventos inscritos no se ve (en la página Mis tickets, luego de iniciar sesión).

## Pasos para reproducir el problema
1- Iniciar sesión
2- Inscribirse a un evento (o estar previamente inscrito a alguno)
3- Ir a sección `Mis Tickets`
4- Ver los tickets para eventos inscritos

## Screenshots
![imagen](https://user-images.githubusercontent.com/86406248/222653171-3ac4c2fa-2e54-4f53-949a-d6a826eb69d1.png)

![imagen](https://user-images.githubusercontent.com/86406248/222653351-01f720a9-48be-468b-b2e3-fd93ae6d24e8.png)

**Comment by linder3hs** [comment]
https://github.com/linder3hs/Tech-Conf/pull/10
